version: '3.8'

services:
  bd:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fin_api
    ports:
      - 5432:5432
